"""init

Revision ID: 7223f63e5bb6
Revises: 
Create Date: 2025-12-24 21:12:18.044191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7223f63e5bb6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_games_likes'), 'games', ['likes'], unique=False)
    op.create_index(op.f('ix_games_rating'), 'games', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_rating'), table_name='games')
    op.drop_index(op.f('ix_games_likes'), table_name='games')
    # ### end Alembic commands ###
